# Generated by Django 2.1 on 2019-12-03 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_', '0002_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_.Class')),
            ],
        ),
    ]
